services:
  postgres:
    image: postgres:latest
    container_name: simple_bank_db
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=wizard
      - POSTGRES_DB=simple_bank
    volumes:
      - ~/Documents/SimpleBank/db_data/dev_db:/var/lib/postgresql/data:rw
    networks:
      simple_bank_net:
        ipv4_address: 10.10.10.5
  
  api:
    build: 
      context: .
      dockerfile: Dockerfile.staged
    image: simple_bank:latest
    container_name: simple_bank_api
    environment:
      - GIN_MODE=release
      - DB_SOURCE=postgresql://wizard:secret@postgres:5432/simple_bank?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      simple_bank_net:
        ipv4_address: 10.10.10.3
networks:
  simple_bank_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24