name: Run Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.22
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build database Docker image
      run: make build-db-img
      working-directory: ./database

    - name: Start PostgreSQL service
      run: |
        make launch-db-con-with-db-create
        docker ps
      working-directory: ./database

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate.linux-amd64 /usr/bin/migrate
        which migrate
    - name: Wait for PostgreSQL to be ready
      run: ./wait-for-it.sh localhost:5432 --timeout=60 --strict -- echo "PostgreSQL is up"
      
    - name: Run migrations
      run: make migrate-up-db-git
      working-directory: ./database

    - name: Test
      run: make test-db
      working-directory: ./database
